name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: [enhancement]
assignees: []

body:
  - type: textarea
    attributes:
      label: Feature Description
      description: What feature would you like to see?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Use case or motivation
